/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppFooter: typeof import('./components/AppFooter.vue')['default']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    NextProject: typeof import('./components/NextProject.vue')['default']
    ProjectContainer: typeof import('./components/ProjectContainer.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Technologies: typeof import('./components/Technologies.vue')['default']
    TechnologyCard: typeof import('./components/TechnologyCard.vue')['default']
  }
}
